### ISSUE TITLE
Bug in filetype detection for archive entries

### ISSUE THREAD

**Issue by Plus1Entropy** [dsoprea/PyEasyArchive#14]
The bug is in libarchive/adapters/archive_entry.py, in the ArchiveEntry class' filetype property, specifically line 99:
> `flags = dict([(k, (v & filetype) > 0)`

This should change to:
`flags = dict([(k, v == filetype)`

The problem is that some of the IF* flags have overlapping bits set, so multiple flags will return `(v & filetype) > 0` as being True. For example, `IFREG = 0100000`, `IFLNK = 0120000`, and `IFSOCK = 0140000`; so if the file is ANY one of these types, all 3 flags will be set.

**Comment by dsoprea** [comment]
Can you submit a PR?

**Comment by dsoprea** [comment]
Merged. Thanks, @Plus1Entropy.
