### ISSUE TITLE
handling symlinks

### ISSUE THREAD

**Issue by SkyLeach** [dsoprea/PyEasyArchive#24]
The filetype information returned is a bit confusing:
```
tmp/symlinktest/
{'IFBLK': True,
 'IFCHR': False,
 'IFDIR': True,
 'IFIFO': False,
 'IFLNK': False,
 'IFREG': False,
 'IFSOCK': True}
'Found dir'
tmp/symlinktest/hosts
{'IFBLK': True,
 'IFCHR': True,
 'IFDIR': False,
 'IFIFO': False,
 'IFLNK': True,
 'IFREG': True,
 'IFSOCK': True}
'Found link'
tmp/symlinktest/just_text.txt
{'IFBLK': False,
 'IFCHR': False,
 'IFDIR': False,
 'IFIFO': False,
 'IFLNK': True,
 'IFREG': True,
 'IFSOCK': True}
'Found regular file'

```

not only is IFLNK set for regular files as well as symlinks, but IFBLK seems to be the trigger if IFDIR is false for links.

In addition, I don't see a way to get the target of a symlink?  simply opening and writing (as in the example) writes a normal 0-length file rather than a symlink.

**Comment by SkyLeach** [comment]
I can't tag this as a question

**Comment by dsoprea** [comment]
libarchive is in charge of setting the flags, and they're not very intuitive to me, either. Half of them represent a single bit and half of them represent multiple bits.

I just added a commit. Here's an example of how to detect and resolve symlinks:

https://github.com/dsoprea/PyEasyArchive/blob/3d546e210d4dd8429b0e6492bb8628ec6e94a7ee/tests/adapters/test_archive_read.py#L78

```python
index = {
    entry.pathname: entry.symlink_targetpath
    for entry
    in e
    if entry.filetype.IFLNK is True
}
```

**Comment by SkyLeach** [comment]
That was definitely not working the last time I checked, but I'll pull this now and check.
