### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [dsoprea/PyEasyArchive#28]
The pypi source archive isn't including the `LICENSE` file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by dsoprea** [comment]
Is there any reason that you can't use the release-archives on the actual release-page on Github (https://github.com/dsoprea/PyEasyArchive/releases)? Those are the official distributables.

**Comment by toddrme2178** [comment]
Although we can use the github releases, we have scripts that monitor pypi packages for updates, which is harder on github, so using pypi packages is better when they are available.  

But overall, the python packaging guidelines say that pypi packages [should have license files](https://packaging.python.org/tutorials/distributing-packages/#license-txt) for legal reasons:

> Every package should include a license file detailing the terms of distribution. In many jurisdictions, packages without an explicit license can not be legally used or distributed by anyone other than the copyright holder.

**Comment by dsoprea** [comment]
Thank you for sharing that. I wasn't aware.

I added it yesterday.
