### ISSUE TITLE
__str__ returns bytes when casting entry to string

### ISSUE THREAD

**Issue by Khalilw1** [dsoprea/PyEasyArchive#29]
Hello,
I tried to use the libarchive wrapper with python 3 but seems like there is conversion problem since the __str__ returns bytes and I wasn't able to decode with both 'utf-8' and 'ascii'. It seems the class also doesn't have any __str__ behavior.
```python
    def _decompress(self, filename):
        path = ('{}/{}'.format(self.dump_path, filename))
        with libarchive.public.file_reader(path) as compressed:
            for entry in compressed:
                with open('{}/{}'.format(self.dump_path, str(entry))) as f:
                    for block in entry.get_blocks():
                        f.write(block)
                # Assumption is made here that stackoverflow files contain a
                # signle file and that is the xml file we want to parse.
                return entry

```

**Comment by Khalilw1** [comment]
I don't know if the project is still being maintained in any way but I was able to successfully use another package to resolve the issue so I think this can be safely closed

**Comment by dsoprea** [comment]
I just haven't had a chance to look at it.


Dustin

**Comment by Khalilw1** [comment]
it seems as though entry returns bytes and I tried to look at the code but couldn't figure it out if you need more details on how I use it I would be happy to help
