### ISSUE TITLE
Not possible to get information about archive? (solid, ...)

### ISSUE THREAD

**Issue by ganego** [dsoprea/PyEasyArchive#42]
At least I cannot find anything regarding this in the examples, and there seems to be no other documentation.

I'd like to request a feature to get more information about an archive, especially information if it's solid or not.

**Comment by dsoprea** [comment]
By "solid", do you mean non-sparse? Remember that libarchive, and, thus, PyEasyArchive, are an abstraction. You're likely gonna have a hard time getting access to stuff that isn't supported by every supported format.

A quick look at the API seems to indicate that it's not possible to get information like this. Feel free to take a look for yourself: https://github.com/libarchive/libarchive/blob/master/libarchive/archive.h

If you happen to find one, feel free to create a PR to add the interfaces for it.

**Comment by ganego** [comment]
In a "normal" archive (all zip for example, or "non-solid" rar/7z) each file is compressed on its own and then concatenated.
In a solid archive the files are first concatenated into one big file and then this one is compressed (basically tar->gz). Can have the advantage of better compression but you need to decompress the whole blob for a single file - so it takes more time to extract single files.

https://en.wikipedia.org/wiki/Solid_compression

I'll try to find some other way.
